version: "3.9"

services:
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    tty: true
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8000:8000
